import type { Metadata } from "next";
import { Inter, Rubik} from "next/font/google";
import { ThemeProvider } from "@/components/misc/(theme)/theme-provider";
import "@/app/globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const rubik =  Rubik({subsets:["latin"], variable:'--font-rubik'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${rubik.variable}`}>
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem 
          disableTransitionOnChange
        >
        <div className="container max-w-3xl mx-auto min-h-screen flex flex-col px-4 py-5">
          <div className="flex-1">
            <Header />
            {children}
          </div>

        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
